import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, Float, Boolean
from app.models.job import Base


class TradeAlert(Base):
    """
    Stores intraday alerts generated by the Live Monitor for top picks.
    Examples: "Stop Loss Hit", "Target Hit".
    """
    __tablename__ = "trade_alerts"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    symbol = Column(String, index=True, nullable=False)
    alert_type = Column(String, nullable=False)   # "STOP_LOSS", "TARGET", "WARNING", "INFO"
    message = Column(String, nullable=False)
    price_at_alert = Column(Float, nullable=False)
    
    # Track the scan date this stock belongs to
    scan_date = Column(String, index=True, nullable=False)
    
    is_read = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
